
spring:
  application:
    name: seungyn
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    logging:
      level:
        org.hibernate.orm.jdbc.bind: trace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigs?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tmddbs3124

openapi:
  service-key: 9SpFR2/nELWRsR606KznXxUyxq/fKoZfiJgVrdOFHfhHtGbErI9MhPVJVsTblmwXHbpaYMCj/hSZs0vxEgZj9g==